name: GitHub Testing OIDC 2nd Attempt ORIGINALLY CREATED BY @Sharif

on:
  push:
    branches: [Testing]

permissions:
  id-token: write
  contents: read    
      
  
jobs:
  verify_user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Verify OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: "us-east-2"
          role-to-assume: ${{ secrets.AWS_OIDC_ACCESS }}
      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      